---
title: "Home"
output:
  html_document:
    toc: false
---

An unpublished analysis of aging [Diversity Outbred](https://www.jax.org/strain/009376) (mouse) kidney/heart expression data.

#### Reports:

* [GLMNET Age/Sex Predictions](predict-glmnet.html) - Could we predict Age and Sex from mRNA/protein expression?
* [Kidney vs. Heart](pvals_kidney_vs_heart.html) - Comparison of Sex and Age dependent genes and proteins.
* [Mediation Examples](examples.html) - A few selected examples of Age/Sex effect on kidney/heart protein expression. 
* [Age/Sex Effect Mediation](new-med-plots.html) - Is Age/Sex Effect On Protein Expression Mediated by RNA? (p-value version)
* [Age/Sex Effect Mediation2](old-med-plots.html) - Is Age/Sex Effect On Protein Expression Mediated by RNA? (LOD version)
* [Histograms](pval-histograms.html) of Sex/Age ANOVA tests' p-values.
* [PCA plots](pca.html) - The scatter plot of the first two principal components for kidney/heart on mRNA-/protein-level.
* [PCA comparisons](pca_comparison.html) - Are PCAs correlated between tissues or levels?

#### Shiny apps:
* [Effect Mediation](http://churchilldev.jax.org:49194/effectmed/) - JAX network only.

#### You can also access:

* [Dataset](https://github.com/simecek/TheAgingProteome/tree/master/data) (Original .RData data files)
* [Processed data](https://github.com/simecek/TheAgingProteome/tree/master/output) (ANOVA & PCA results)
* [Scripts](https://github.com/simecek/TheAgingProteome/tree/master/code) and [Makefile](https://github.com/simecek/TheAgingProteome/blob/master/Makefile) used for data processing
* [RMarkdown files](https://github.com/simecek/TheAgingProteome/tree/master/analysis) generating the reports above 