---
title: "Is Age/Sex Effect Mediated by RNA? (p-value version)"
author: "Petr Simecek"
output: html_document
---

```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

```{r knitr-opts-chunk, include=FALSE}
```

**Last updated:** `r Sys.Date()`

**Code version:** `r workflowr::extract_commit(".", 1)$sha1`

** WARNING - SOMETHING IS WRONG HERE **

This is the analysis of Age/Sex effect mediation by mRNA using p-values (new version). All plots are (will be) interactive (tooltip = gene symbol) and have been generated from R/Markdown file [new-med-plots.Rmd](https://github.com/simecek/TheAgingProteome/blob/master/analysis/new-med-plots.Rmd).

## Kidney

```{r kidney, echo=FALSE}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(plotly))
suppressPackageStartupMessages(library(scales))

# -log10(p) transformation for ggplot
reverselog_trans <- function(base = exp(1)) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv, 
              log_breaks(base = base), 
              domain = c(1e-100, Inf))
}

# read ANOVA table - kidney
dt <- read.csv("../../kidney2/kidney_anova_table.csv", as.is = TRUE) %>%
  select(symbol, starts_with("p.Prot_Age"),
         starts_with("p.Prot_Sex"))

# gathering `dt` from 4 cols to 2 cols (->ggplot)
tmp1 <- select(dt, symbol, starts_with("p.Prot_Age"))
tmp2 <- select(dt, symbol, starts_with("p.Prot_Sex"))
names(tmp1) <- names(tmp2) <- c("symbol", "y", "x")
tmp1$var <- "Age"
tmp2$var <- "Sex"
dt2 <- rbind(tmp1, tmp2)

eps <- 0.0000001
pl <- ggplot(dt2, aes(x=x+eps, y=y+eps,text=symbol)) +
  geom_point(alpha=0.2) + 
  geom_abline(intercept = 0, slope = 1, color="red") +
  scale_x_continuous(trans=reverselog_trans(10)) +
  scale_y_continuous(trans=reverselog_trans(10)) +
  facet_wrap(~var) +
  xlab("LOD(Protein ~ X)") +
  ylab("LOD(Protein ~ X | mRNA)") +
  theme_bw()
pl
#ggplotly(pl, tooltip="text")
```

## Heart

```{r heart, echo=FALSE}

# read ANOVA table - heart
dt <- read.csv("../../heart2/heart_anova_table.csv", as.is = TRUE) %>%
  select(symbol, starts_with("p.Prot_Age"),
         starts_with("p.Prot_Sex"))

# gathering `dt` from 4 cols to 2 cols (->ggplot)
tmp1 <- select(dt, symbol, starts_with("p.Prot_Age"))
tmp2 <- select(dt, symbol, starts_with("p.Prot_Sex"))
names(tmp1) <- names(tmp2) <- c("symbol", "y", "x")
tmp1$var <- "Age"
tmp2$var <- "Sex"
dt2 <- rbind(tmp1, tmp2)

eps <- 0.0000001
pl <- ggplot(dt2, aes(x=x+eps, y=y+eps,text=symbol)) +
  geom_point(alpha=0.2) + 
  geom_abline(intercept = 0, slope = 1, color="red") +
  scale_x_continuous(trans=reverselog_trans(10)) +
  scale_y_continuous(trans=reverselog_trans(10)) +
  facet_wrap(~var) +
  xlab("LOD(Protein ~ X)") +
  ylab("LOD(Protein ~ X | mRNA)") +
  theme_bw()
pl
#ggplotly(pl, tooltip="text")
```


## Session Information

```{r session-info}
```
